# BDD Scenarios: НутриМайнд
# Generated by requirements-validator

# ============================================================
# EPIC 1: ONBOARDING & AUTH
# ============================================================

Feature: Telegram Authentication
  As a Telegram user
  I want to open the Mini App and be automatically authenticated
  So that I can start using the app with zero friction

  Background:
    Given the НутриМайнд bot is running
    And the Mini App URL is configured in @BotFather

  @happy-path @critical @US-1.1
  Scenario: Successful authentication via Telegram initData
    Given I am a Telegram user with id 123456789
    When I open the Mini App from the bot's "Открыть" button
    Then the frontend sends initData to POST /api/auth/telegram
    And the backend validates HMAC-SHA256 signature using BOT_TOKEN
    And I receive a JWT token within 500ms
    And I am redirected to AI Interview (first time) or Dashboard (returning)

  @happy-path @US-1.1
  Scenario: Returning user skips onboarding
    Given I am an authenticated user with onboarding_complete = true
    When I open the Mini App
    Then I am redirected directly to the Dashboard
    And my previous session data is preserved

  @error-handling @US-1.1
  Scenario: Expired initData rejected
    Given my initData auth_date is older than 300 seconds
    When the backend validates the initData
    Then I receive 401 with error code "INVALID_INIT_DATA"
    And no JWT is issued
    And the frontend requests fresh initData from Telegram SDK

  @error-handling @US-1.1
  Scenario: Tampered initData rejected
    Given initData with modified hash field
    When the backend validates HMAC-SHA256
    Then the calculated hash does not match
    And I receive 401 with error code "INVALID_INIT_DATA"
    And the attempt is logged (without PII)

  @edge-case @US-1.1
  Scenario: Mini App opened outside Telegram
    Given I open https://app.nutrimind.ru directly in a browser
    When the frontend cannot access Telegram WebApp object
    Then I see message "Откройте через Telegram"
    And a link to t.me/nutrimind_bot is displayed

  @security @US-1.1
  Scenario: Rate limiting on auth endpoint
    Given I send 11 requests to POST /api/auth/telegram within 1 minute
    Then the 11th request receives 429 Too Many Requests
    And retry_after header indicates wait time in seconds

# ============================================================

Feature: AI Interview (Onboarding)
  As a new user
  I want to answer 2 questions about my eating habits
  So that the AI can start building my pattern profile

  Background:
    Given I am authenticated via Telegram
    And my onboarding_complete is false

  @happy-path @critical @US-1.2
  Scenario: Complete AI interview
    Given I am on the interview screen
    When I select an answer for question 1 (eating schedule type)
    And I select an answer for question 2 (biggest challenge)
    And I tap "Готово"
    Then my answers are saved to ai_profiles.interview_answers
    And a cluster_id is assigned based on my answers
    And onboarding_complete is set to true
    And I am redirected to Dashboard with prompt "Запишите первый приём пищи"
    And the process completes within 2 seconds

  @error-handling @US-1.2
  Scenario: Incomplete interview submission
    Given I have answered only question 1
    When I try to submit
    Then I see validation error "Ответьте на все вопросы"
    And I remain on the interview screen

  @edge-case @US-1.2
  Scenario: App closed mid-interview
    Given I have answered question 1 but not question 2
    When I close the Mini App and reopen it
    Then I see the interview screen with question 1 pre-filled
    And I can continue from question 2

# ============================================================
# EPIC 2: FOOD LOGGING
# ============================================================

Feature: Text-based Food Logging
  As a user
  I want to log what I ate by typing in Russian
  So that the AI can track my eating patterns

  Background:
    Given I am an authenticated user on the Dashboard
    And I have completed onboarding

  @happy-path @critical @US-2.1
  Scenario: Log a simple Russian meal
    Given I tap the "+" button
    When I type "борщ с хлебом"
    And I tap "Записать"
    Then the text is parsed into 2 food items within 3 seconds
    And I see: борщ (~150 kcal, green) and хлеб (~80 kcal, yellow)
    And the entry is saved with current timestamp
    And total calories (230) are displayed

  @happy-path @US-2.1
  Scenario: Log meal with AI fallback
    Given I type "тофу в кисло-сладком соусе"
    And the food is not in the local database
    When the AI parser is called
    Then it returns estimated calories within 5 seconds
    And the food item is displayed with calorie estimate
    And confidence indicator shows "AI оценка"

  @error-handling @US-2.1
  Scenario: Empty food input
    When I tap "Записать" with empty text field
    Then I see validation error "Введите что вы съели"
    And no entry is saved

  @error-handling @US-2.1
  Scenario: Non-food text input
    When I type "привет как дела"
    And the parser returns low confidence (< 0.3)
    Then I see message "Уточните что вы съели"
    And the entry is not saved

  @error-handling @US-2.1
  Scenario: AI parser timeout
    Given the OpenAI API is slow (> 5s)
    When I submit a food entry not in the local DB
    Then the entry is saved with raw_text only
    And I see "Калории рассчитываются..."
    And the parsing is queued as async job
    And I am notified when parsing completes

  @edge-case @US-2.1
  Scenario: Very long food description
    When I type a food description longer than 500 characters
    Then the input is truncated to 500 characters
    And the first items are parsed normally

  @edge-case @US-2.1
  Scenario: Duplicate entry within 1 minute
    Given I logged "каша с маслом" 30 seconds ago
    When I try to log "каша с маслом" again
    Then I see confirmation "Вы уже записали это. Добавить ещё раз?"
    And I can confirm or cancel

  @edge-case @US-2.1
  Scenario Outline: Food category color assignment
    When I log "<food>"
    Then it is categorized as "<color>"

    Examples:
      | food         | color  | reason                    |
      | огурец       | green  | caloric density < 1.0     |
      | гречка       | yellow | caloric density 1.0-2.5   |
      | шоколад      | orange | caloric density > 2.5     |

# ============================================================

Feature: Contextual Logging
  As a user
  I want to log my mood and context when eating
  So that the AI can find correlations between emotions and eating

  @happy-path @critical @US-2.2
  Scenario: Log meal with mood and context
    Given I am logging a meal "пельмени"
    When I select mood "😟" (meh) and context "работа"
    And I tap "Записать"
    Then the entry is saved with mood="meh" and context="work"
    And mood and context appear in my food history

  @happy-path @US-2.2
  Scenario: Log meal without mood and context
    Given I am logging a meal "салат"
    When I do not select mood or context
    And I tap "Записать"
    Then the entry is saved with mood=null and context=null
    And no error is shown

  @edge-case @US-2.2
  Scenario: Change mood after submission
    Given I logged a meal 5 minutes ago without mood
    When I tap on the entry in history
    Then I can add or change mood and context
    And the updated values are saved

# ============================================================
# EPIC 3: AI PATTERN DETECTION
# ============================================================

Feature: Pattern Discovery
  As a user
  I want the AI to find my personal overeating patterns
  So that I understand WHY I overeat

  Background:
    Given I am an authenticated paid subscriber

  @happy-path @critical @US-3.1
  Scenario: Pattern detected after sufficient data
    Given I have logged food for 7 days with 25 entries
    And I consistently eat >60% of daily calories after 18:00
    When the Pattern Detector runs (daily at 03:00)
    Then it identifies pattern type="time" with confidence ≥ 0.5
    And description is ≤ 50 words in plain Russian
    And the detection completes within 30 seconds
    And the pattern appears on my Dashboard

  @happy-path @US-3.1
  Scenario: Mood-based pattern detected
    Given I have 15+ entries where mood="bad" correlates with calories > 1.5x average
    When the Pattern Detector runs
    Then it identifies pattern type="mood"
    And description includes reference to mood correlation
    And confidence reflects the statistical strength

  @error-handling @US-3.1
  Scenario: Insufficient data for pattern detection
    Given I have fewer than 10 food entries
    When the Pattern Detector runs
    Then it uses cold-start cluster patterns
    And displays disclaimer "Предварительный анализ"
    And confidence is capped at 0.4

  @edge-case @US-3.1
  Scenario: No patterns found despite sufficient data
    Given I have 30+ entries with uniform eating behavior
    When the Pattern Detector runs
    Then it shows message "Ваше питание стабильно — отличная работа!"
    And suggests general CBT tips instead

  @edge-case @US-3.1
  Scenario: User disputes a pattern
    Given I see a pattern "Стресс → переедание"
    When I tap "Это неверно"
    Then the pattern confidence is reduced by 0.2
    And my feedback is logged for model improvement
    And if confidence drops below 0.3, pattern is deactivated

# ============================================================

Feature: Daily AI Insights
  As a user
  I want to receive a daily AI insight based on my data
  So that I learn something new about my habits each day

  Background:
    Given I am an authenticated user with 3+ days of data
    And today's insight has been pre-generated at 06:00

  @happy-path @critical @US-3.2
  Scenario: View today's AI insight
    When I open the Dashboard
    Then I see today's insight card within 100ms (served from cache)
    And the insight references at least 1 specific entry or pattern from my data
    And it includes exactly 1 concrete recommendation (verb + object + timing)
    And the insight text is 2-4 sentences (≤ 100 words)

  @happy-path @US-3.2
  Scenario: Insight rotation across types
    Given I have received insights for 6 consecutive days
    Then the insight types follow rotation:
      | Day | Type     |
      | 1-3 | pattern  |
      | 4-5 | progress |
      | 6   | cbt      |
      | 7   | risk     |

  @error-handling @US-3.2
  Scenario: AI service unavailable
    Given the OpenAI API is down
    When I open the Dashboard
    Then I see the most recent cached insight
    And a note "Обновляется..." is displayed
    And insight generation is retried every 15 minutes

  @edge-case @US-3.2
  Scenario: User rates insight negatively
    Given I see today's insight
    When I tap 👎
    Then feedback is recorded
    And future insights adjust to avoid similar patterns
    And I see a brief "Спасибо за отзыв" confirmation

# ============================================================

Feature: Risk Prediction
  As a user
  I want to know when I'm at high risk of overeating today
  So that I can prepare and prevent a binge

  Background:
    Given I am an authenticated user with detected patterns

  @happy-path @critical @US-3.3
  Scenario: High risk alert displayed
    Given my patterns include "skip lunch → evening overeating"
    And I have not logged lunch by 15:00
    When the Risk Predictor calculates today's risk
    Then risk score is > 0.6 (high)
    And I see a "Trigger Alert" card on Dashboard
    And the alert includes a CBT micro-exercise

  @happy-path @US-3.3
  Scenario: Push notification before risk window
    Given a high-risk time window predicted at 18:00
    When the clock reaches 17:30
    Then I receive a Telegram push notification within 60 seconds
    And the message says "Сегодня высокий риск срыва в 18:00"
    And tapping the notification opens the Mini App Dashboard

  @error-handling @US-3.3
  Scenario: No patterns detected yet
    Given I have no detected patterns
    When I view the risk section on Dashboard
    Then I see placeholder "Собираю данные..."
    And no risk score is displayed

  @edge-case @US-3.3
  Scenario: Risk decreases after healthy action
    Given my risk score is 0.7 (high)
    When I complete a CBT lesson today
    Then risk is recalculated with factor *= 0.8
    And the new risk score is 0.56 (medium)
    And the Dashboard reflects the updated level

  @edge-case @US-3.3
  Scenario: Weekend risk amplification
    Given I have a weekend overeating pattern
    And today is Saturday
    When the Risk Predictor runs
    Then the weekend factor *= 1.3 is applied
    And I receive appropriate warning

# ============================================================
# EPIC 4: CBT LESSONS
# ============================================================

Feature: Daily CBT Mini-Lesson
  As a user
  I want a 5-minute daily CBT lesson
  So that I learn to change my relationship with food

  Background:
    Given I am an authenticated paid subscriber

  @happy-path @critical @US-4.1
  Scenario: Complete a CBT lesson
    Given I have completed 5 out of 20 lessons
    When I tap on today's lesson (lesson 6)
    Then the lesson content loads within 1 second
    And I see lesson text with interactive elements
    And the lesson is tagged with at least 1 of my active pattern types
    And I can complete it in 3-7 minutes
    And after completion, progress shows "6/20 уроков"

  @happy-path @US-4.1
  Scenario: Lesson relevance based on patterns
    Given my detected patterns include type="mood"
    When I view available lessons
    Then lessons tagged with "mood" are prioritized
    And the recommended lesson matches my patterns

  @error-handling @US-4.1
  Scenario: Free user tries to access lesson beyond limit
    Given I am a free user
    And I have received 3 AI insights (paywall threshold)
    When I tap on a CBT lesson
    Then I see the paywall screen
    And the lesson content is not displayed

  @edge-case @US-4.1
  Scenario: All 20 lessons completed
    Given I have completed all 20 lessons
    When I tap on the lessons section
    Then I see "Поздравляем! Все уроки пройдены"
    And I can review any previous lesson
    And a "начать заново" option is available

# ============================================================
# EPIC 5: PAYWALL & SUBSCRIPTION
# ============================================================

Feature: Freemium Paywall
  As a free user
  I want to experience 3 AI insights before being asked to pay
  So that I see the value before committing

  @happy-path @critical @US-5.1
  Scenario: Paywall triggered after 3rd insight
    Given I am a free user
    And I have received exactly 3 AI insights
    When I try to view the 4th insight
    Then I see the paywall screen
    And it displays pricing: "499 ₽/мес" and "3990 ₽/год"
    And I see a list of Premium features
    And I see a "Подписаться" button (Telegram Stars)
    And I see a "Оплатить картой" link (ЮKassa fallback)

  @happy-path @US-5.1
  Scenario: Successful subscription via Telegram Stars
    Given I am on the paywall screen
    When I tap "Подписаться" and complete Telegram Stars payment
    Then my subscription_status changes to "standard"
    And subscription_expires_at is set to 30 days from now
    And the 4th insight is immediately unlocked
    And I am redirected to Dashboard

  @error-handling @US-5.1
  Scenario: Payment failure
    Given I tap "Подписаться"
    When the Telegram Stars payment fails
    Then I see error message "Оплата не прошла"
    And I see option "Попробовать снова" and "Оплатить картой"
    And my subscription_status remains "free"

  @happy-path @US-5.1
  Scenario: Dismiss paywall
    Given I see the paywall screen
    When I tap "Позже" or swipe back
    Then I return to Dashboard
    And limited features remain available
    And paywall is shown again on next locked content access

  @edge-case @US-5.1
  Scenario: Free insights counter accuracy
    Given I am a free user with insights_received = 2
    When I view today's insight (3rd)
    Then is_locked is false (insight visible)
    And insights_received increments to 3
    And next insight will trigger paywall

# ============================================================

Feature: Subscription Management
  As a paid subscriber
  I want to manage my subscription easily
  So that I never feel trapped

  Background:
    Given I am an authenticated paid subscriber

  @happy-path @critical @US-5.2
  Scenario: View subscription details
    Given my plan is "standard" expiring on 2026-03-15
    When I navigate to Settings → Subscription
    Then the page loads within 1 second
    And I see "Тариф: Стандарт"
    And I see "Следующее списание: 15 марта 2026"
    And I see "Отменить подписку" button

  @happy-path @US-5.2
  Scenario: Cancel subscription in 1 tap
    When I tap "Отменить подписку"
    Then I see confirmation dialog "Вы уверены? Подписка будет активна до конца оплаченного периода"
    When I confirm cancellation
    Then subscription status changes to "cancelled"
    And I see "Подписка активна до {expires_at}"
    And I receive Telegram Bot message confirming cancellation

  @error-handling @US-5.2
  Scenario: Cancel subscription fails
    Given the payment provider is unavailable
    When I try to cancel
    Then I see "Не удалось отменить. Попробуйте позже"
    And my subscription remains active
    And the error is logged

  @edge-case @US-5.2
  Scenario: Subscription expired
    Given my subscription expired yesterday
    When I open the app
    Then I am treated as a free user
    And I see "Подписка истекла" banner with "Продлить" button
    And my data is preserved

# ============================================================
# EPIC 6: INVITE SYSTEM
# ============================================================

Feature: Invite a Friend
  As a user
  I want to invite a friend for paired AI analysis
  So that we can support each other

  @happy-path @critical @US-6.1
  Scenario: Generate and share invite link
    Given I am on the invite screen
    When I tap "Пригласить"
    Then a Telegram share dialog opens
    And the message contains deep link t.me/nutrimind_bot?start=invite_{CODE}
    And the invite_code is saved to the invites table

  @happy-path @US-6.1
  Scenario: Friend redeems invite
    Given my friend opens t.me/nutrimind_bot?start=invite_ABC123
    And the invite code ABC123 is valid and unredeemed
    When my friend completes registration
    Then both users receive 7 days of Premium subscription
    And invitee_id is set on the invite record
    And both users receive Telegram Bot confirmation message

  @error-handling @US-6.1
  Scenario: Invitee already registered
    Given user with telegram_id 987654321 is already registered
    When they open an invite link
    Then they see "Вы уже зарегистрированы"
    And no Premium reward is granted to either user

  @error-handling @US-6.1
  Scenario: Invalid or expired invite code
    Given invite code "INVALID123" does not exist in the database
    When a user opens t.me/nutrimind_bot?start=invite_INVALID123
    Then they see "Ссылка недействительна"
    And they can still register normally

  @edge-case @US-6.1
  Scenario: Self-invite attempt
    Given I generated invite code "MY_CODE"
    When I open t.me/nutrimind_bot?start=invite_MY_CODE myself
    Then the invite is rejected with "Нельзя использовать собственное приглашение"

  @edge-case @US-6.1
  Scenario: Rate limit on invite generation
    Given I have generated 5 invite codes today
    When I try to generate a 6th
    Then I see "Лимит приглашений на сегодня исчерпан"
    And the request is rejected with 429

# ============================================================
# EPIC 7: DATA PRIVACY (152-ФЗ)
# ============================================================

Feature: Data Export
  As a user
  I want to download all my data
  So that I comply with my right of access under 152-ФЗ

  @happy-path @critical @US-7.1
  Scenario: Request data export
    Given I am an authenticated user
    When I tap "Экспорт данных" in Settings
    Then I see "Подготовка данных..."
    And within 24 hours I receive a Telegram message with JSON file download
    And the file contains: profile, food entries, patterns, insights, lesson progress

Feature: Account Deletion
  As a user
  I want to delete my account and all data permanently
  So that I exercise my right to erasure under 152-ФЗ

  @happy-path @critical @US-7.2
  Scenario: Delete account
    Given I am an authenticated user
    When I tap "Удалить аккаунт" in Settings
    Then I see confirmation "Все данные будут удалены безвозвратно"
    When I confirm by typing "УДАЛИТЬ"
    Then all my data is cascade-deleted from all tables within 72 hours
    And my active subscription is cancelled
    And I receive final Telegram confirmation
    And I am logged out of the Mini App
