"""Invite router – referral code generation and redemption."""

from fastapi import APIRouter, HTTPException

from app.dependencies import CurrentUser, DbSession
from app.schemas.invite import (
    InviteGenerateResponse,
    MyInvitesResponse,
    RedeemRequest,
    RedeemResponse,
)
from app.services.invite_service import (
    build_share_url,
    generate_invite as svc_generate_invite,
    get_my_invites as svc_get_my_invites,
    PREMIUM_DAYS,
    redeem_invite as svc_redeem_invite,
)

router = APIRouter(prefix="/api/invite", tags=["invite"])


@router.post("/generate", response_model=InviteGenerateResponse)
async def generate_invite(
    db: DbSession,
    current_user: CurrentUser,
) -> InviteGenerateResponse:
    """Generate a unique invite code for the current user."""
    invite = await svc_generate_invite(db, current_user["user_id"])
    return InviteGenerateResponse(
        invite_code=invite.invite_code,
        share_url=build_share_url(invite.invite_code),
    )


@router.post("/redeem", response_model=RedeemResponse)
async def redeem_invite(
    body: RedeemRequest,
    db: DbSession,
    current_user: CurrentUser,
) -> RedeemResponse:
    """Redeem an invite code.

    Both the inviter and the invitee receive 7-day premium.
    """
    invite = await svc_redeem_invite(db, body.invite_code, current_user["user_id"])
    if invite is None:
        raise HTTPException(
            status_code=400,
            detail="Invalid or already redeemed invite code.",
        )
    return RedeemResponse(
        status="ok",
        message="Invite redeemed successfully",
        premium_days=PREMIUM_DAYS,
    )


@router.get("/my", response_model=MyInvitesResponse)
async def my_invites(
    db: DbSession,
    current_user: CurrentUser,
) -> MyInvitesResponse:
    """Return all invites generated by the current user."""
    data = await svc_get_my_invites(db, current_user["user_id"])
    return MyInvitesResponse(**data)
